const routesFront = {
  about: 'about',
  activeLicenses: 'active-licenses',
  briefProgramContents: 'brief-program-contents',
  checkLicenses: 'check-licenses',
  contactForm: 'contact-form',
  contacts: 'contacts',
  cta: 'cta',
  desc: 'desc',
  diplomas: 'diplomas',
  faq: 'faq',
  filterSearch: 'filter-search',
  forWhom: 'for-whom',
  fullProgram: 'full-program',
  helpWithEmployment: 'help-with-employment',
  hero: 'hero',
  heroProgram: 'hero-program',
  heroPrograms: 'hero-programs',
  howProcessGoes: 'how-process-goes',
  legalDocs: 'legal-docs',
  legalInfo: 'legal-info',
  meetYourTeachers: 'meet-your-teachers',
  paymentBtns: 'payment-btns',
  paymentDebitCard: 'payment-debit-card',
  paymentInfo: 'payment-info',
  programs: 'programs',
  reviews: 'reviews',
  studyCost: 'study-cost',
  teachers: 'teachers',
  trustedBy: 'trusted-by',
  webinars: 'webinars',
  webinarsAlt: 'webinars-alt',
  whatYouWillLearn: 'what-you-will-learn',
  whyBother: 'why-bother',
  yourDiploma: 'your-diploma',
  yourFutureJob: 'your-future-job',
  yourResume: 'your-resume'
}

export default routesFront
